//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retailbank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class castleaccount33
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public castleaccount33()
        {
            this.transaction33 = new HashSet<transaction33>();
        }
    
        public int AccountId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string AccountType { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public string ShowMessage { get; set; }
        public string AccountStatus { get; set; }
        public Nullable<int> Balance { get; set; }
    
        public virtual Custdet_1288 Custdet_1288 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction33> transaction33 { get; set; }
    }
}
