//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retailbank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custdet_1288
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Custdet_1288()
        {
            this.castleaccount33 = new HashSet<castleaccount33>();
        }
    
        public int custid { get; set; }
        public Nullable<long> custSsnId { get; set; }
        public string custName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public string DisplayMessage { get; set; }
        public string AccountStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<castleaccount33> castleaccount33 { get; set; }
    }
}
