//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retailbank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction33
    {
        public long TransactionId { get; set; }
        public Nullable<int> TransAccountId { get; set; }
        public string TransDescription { get; set; }
        public Nullable<System.DateTime> Transdate { get; set; }
        public Nullable<long> TransAmount { get; set; }
    
        public virtual castleaccount33 castleaccount33 { get; set; }
    }
}
